################################################################################
- name: Run a module from inside a collection
  hosts: localhost
  tasks:
    - name: Gather some real Facts.
      newswangerd.collection_demo.real_facts:
        name: John Snow
      register: testout
    - debug:
        msg: "{{ testout }}"

################################################################################
- name: Run a module from inside a collection using the collections keyword
  hosts: localhost
  collections:
    - newswangerd.collection_demo
  tasks:
    - name: Gather some real Facts.
      real_facts:
        name: Jane Doe
      register: testout
    - debug:
        msg: "{{ testout }}"

################################################################################
- name: Run a role from inside of a collection
  hosts: localhost
  roles:
    - "newswangerd.collection_demo.factoid"
